# Generated by Django 3.0.8 on 2020-07-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaid_app', '0002_useraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='official_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
