# Generated by Django 3.0.8 on 2020-07-19 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plaid_app', '0003_auto_20200719_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField()),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('subtype', models.CharField(max_length=50)),
                ('iso_currency_code', models.CharField(max_length=10)),
                ('account_id', models.CharField(max_length=50, unique=True)),
                ('official_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=100, null=True)),
                ('item_id', models.CharField(max_length=100, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
        migrations.AddField(
            model_name='account',
            name='user_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='plaid_app.UserItem'),
        ),
    ]
