# Generated by Django 3.0.8 on 2020-07-19 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plaid_app', '0005_auto_20200719_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='public_token',
        ),
    ]
